### ISSUE TITLE
Documentation updates/changes

### ISSUE THREAD

**Issue by jamesmorgan** [knownorigin/docs.knownorigin.io#11]
* Remove the word `dick` from here https://docs.knownorigin.io/guide/code-of-conduct/#what-is-a-code-of-conduct

* Add list of things you need to apply to here - https://docs.knownorigin.io/guide/joining-ko-as-an-artist/#how-to-apply

* Spelling mistake on private keys bit in FAQ: EVERY to EVER

* DROPS FIRE, should be FIRE DROPS to match the site

* Expand on this section a little - https://docs.knownorigin.io/guide/creating-editions/#promoting-your-work e.g. a comment from some on discord about this included:
	* Can we also link to other guides or docs on the subject?
```
Uniqueness/Rarity
Popularity/Reputation of artist
Edition size
Time spent on work

Though these are only a few of the factors that can guide the pricing of work in this space the ultimate decider is you and what you would be happy to accept for it. Initially setting your work to offers only may be a valuable method of price discovery. You might also want to look at how your peers who are selling on KO price their work keeping in mind the criteria above.
```

**Comment by TawfikYasser** [comment]
Hi @jamesmorgan 
Can I help with these updates?
